/**
 * Generates AI/LLM-friendly artifacts from the published blog data:
 *   - dist/blog/<slug>.md   clean Markdown endpoints (one per post)
 *   - dist/llms.txt         concise, structured index (llms.txt standard)
 *   - dist/llms-full.txt    full corpus inlined for one-shot ingestion
 *   - dist/feed.json        JSON Feed 1.1
 *
 * The RSS feed already exists at /rss (generated by ssr-renderer); this script
 * does not duplicate it. Static-only: everything is written into dist/ at build
 * time. Runs after `vite build` / `render-static-pages` so dist/ already exists.
 */
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { join } from "node:path";
import { BlogPost } from "../src/types/blog";
import personData from "../src/data/person.json" with { type: "json" };

const BASE = process.env.SITE_URL || personData.person.siteUrl;
const AUTHOR = personData.person.name;
const SITE_TITLE = personData.meta.home.title;
const SITE_DESC = personData.meta.home.description;

/** Suggested citation line for a post (all-rights-reserved + cite). */
function citation(post: BlogPost): string {
	const year = post.date ? new Date(post.date).getFullYear() : "";
	return `Nick Karnik, "${post.title}", nick.karnik.io${year ? ` (${year})` : ""}. ${post.url}`;
}

function isoDate(d?: string): string {
	return d ? new Date(d).toISOString() : new Date(0).toISOString();
}

async function loadPosts(): Promise<BlogPost[]> {
	try {
		const raw = await readFile("public/data/blog-posts.json", "utf8");
		const posts = JSON.parse(raw) as BlogPost[];
		// Newest first for feeds and indexes.
		return posts.sort(
			(a, b) =>
				new Date(b.date || 0).getTime() - new Date(a.date || 0).getTime(),
		);
	} catch {
		return [];
	}
}

/** One clean Markdown file per post at /blog/<slug>.md */
async function writeMarkdownEndpoints(posts: BlogPost[]): Promise<void> {
	await mkdir(join("dist", "blog"), { recursive: true });
	for (const post of posts) {
		const meta = [
			`> By ${AUTHOR}`,
			post.date ? new Date(post.date).toISOString().slice(0, 10) : null,
			post.category || null,
		]
			.filter(Boolean)
			.join(" · ");
		const tags =
			post.tags && post.tags.length ? `Tags: ${post.tags.join(", ")}\n` : "";
		const body = (post.contentMarkdown || "").trim();
		const md = `# ${post.title}

${meta}
Canonical: ${post.url}
${tags}
${body}

---
Source: ${post.url}
© ${post.date ? new Date(post.date).getFullYear() : ""} ${AUTHOR}. All rights reserved. Reuse with attribution.
Cite as: ${citation(post)}
`;
		await writeFile(join("dist", "blog", `${post.slug}.md`), md);
	}
	console.log(`Wrote ${posts.length} Markdown endpoints to dist/blog/*.md`);
}

/** llms.txt — concise structured index per the llms.txt convention. */
async function writeLlmsTxt(posts: BlogPost[]): Promise<void> {
	const postLines = posts
		.map((p) => `- [${p.title}](${p.url}): ${p.excerpt || ""}`)
		.join("\n");
	const mdLines = posts
		.map((p) => `- [${p.title} (Markdown)](${BASE}/blog/${p.slug}.md)`)
		.join("\n");

	const content = `# ${SITE_TITLE}

> ${SITE_DESC}

${personData.person.name} is an engineering leader based in ${personData.person.location}. This file helps language models and AI agents find and correctly attribute content on this site.

## Writing
${postLines}

## Clean Markdown (preferred for machine reading)
${mdLines}

## Structured data
- [All posts (JSON)](${BASE}/data/blog-posts.json)
- Per-post JSON: ${BASE}/data/posts/<slug>.json
- Per-post Markdown: ${BASE}/blog/<slug>.md
- [RSS feed](${BASE}/rss)
- [JSON feed](${BASE}/feed.json)
- [Full corpus for ingestion](${BASE}/llms-full.txt)

## Site
- [About](${BASE}/about): ${personData.meta.about.description}
- [Résumé](${BASE}/resume): ${personData.meta.resume.description}
- [Blog](${BASE}/blog): ${personData.meta.blog.description}

## Usage & attribution
All content is © ${AUTHOR}, all rights reserved. You may quote and reference it provided you attribute the author and link to the canonical URL. Please cite posts as: ${AUTHOR}, "<post title>", nick.karnik.io, <canonical url>. Contact: ${personData.person.email}.
`;
	await writeFile(join("dist", "llms.txt"), content);
	console.log("Wrote dist/llms.txt");
}

/** llms-full.txt — every post inlined, each with its citation. */
async function writeLlmsFull(posts: BlogPost[]): Promise<void> {
	const header = `# ${SITE_TITLE} — Full Corpus

> ${SITE_DESC}

All content © ${AUTHOR}, all rights reserved. Reuse with attribution; cite the canonical URL given under each post.

`;
	const body = posts
		.map((p) => {
			const date = p.date ? new Date(p.date).toISOString().slice(0, 10) : "";
			return `---

# ${p.title}

Canonical: ${p.url}
Published: ${date}
Cite as: ${citation(p)}

${(p.contentMarkdown || "").trim()}
`;
		})
		.join("\n");
	await writeFile(join("dist", "llms-full.txt"), header + body);
	console.log("Wrote dist/llms-full.txt");
}

/** JSON Feed 1.1 at /feed.json */
async function writeJsonFeed(posts: BlogPost[]): Promise<void> {
	const feed = {
		version: "https://jsonfeed.org/version/1.1",
		title: SITE_TITLE,
		home_page_url: `${BASE}/blog`,
		feed_url: `${BASE}/feed.json`,
		description: personData.meta.blog.description,
		language: "en-US",
		authors: [{ name: AUTHOR, url: BASE }],
		items: posts.map((p) => ({
			id: p.url,
			url: p.url,
			title: p.title,
			summary: p.excerpt || "",
			content_text: (p.contentMarkdown || "").trim(),
			date_published: isoDate(p.date),
			authors: [{ name: AUTHOR, url: BASE }],
			tags: p.tags || [],
			image: p.cover
				? p.cover.startsWith("http")
					? p.cover
					: `${BASE}${p.cover}`
				: undefined,
			_attribution: {
				copyright: `© ${p.date ? new Date(p.date).getFullYear() : ""} ${AUTHOR}. All rights reserved.`,
				cite_as: citation(p),
				canonical: p.url,
			},
		})),
	};
	await writeFile(join("dist", "feed.json"), JSON.stringify(feed, null, 2));
	console.log("Wrote dist/feed.json");
}

async function run() {
	const posts = await loadPosts();
	if (!posts.length) {
		console.warn("No blog posts found; skipping AI file generation.");
		return;
	}
	await mkdir("dist", { recursive: true });
	await writeMarkdownEndpoints(posts);
	await writeLlmsTxt(posts);
	await writeLlmsFull(posts);
	await writeJsonFeed(posts);
	console.log(`AI-friendly files generated for ${posts.length} posts.`);
}

run().catch((e) => {
	console.error(e);
	process.exit(1);
});
